[tox]
envlist = py311, ruff

[testenv:ruff]
dependency_groups =
    lint
recreate = False
setenv =
    STAGE = TEST
    PIP_EXTRA_INDEX_URL = {env:INDEX_URL:}
    PIP_NO_CACHE_DIR = 0
    PYTHONPATH = {toxinidir}/src
commands = ruff check --show-fixes src

[testenv:ty]
dependency_groups =
    lint

recreate = False
setenv =
    PYTHONPATH = {toxinidir}/src
commands = ty check src

[testenv]
basepython = py311
runner = uv-venv-lock-runner
passenv =
    TC_HOST
requires =
    keyring
    tox-uv
setenv =
    PYTHONPATH = {toxinidir}/src
    PIP_EXTRA_INDEX_URL = {env:INDEX_URL:}
    PIP_NO_CACHE_DIR = 0

[testenv:py311]
dependency_groups =
    test
passenv =
    UV_INDEX_URL
    INDEX_URL
commands =
    pytest --basetemp={envtmpdir} --cov=src --cov-report=term-missing tests
