ARG UV_IMAGE=ghcr.io/astral-sh/uv:python3.11-trixie-slim
FROM ${UV_IMAGE} AS fastbpmn-base

# ----------------------------------------------------------------------
# Setup a non root user for execution
RUN adduser -D -s /bin/sh fastbpmn
WORKDIR /home/fastbpmn
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Install libmagic (required for file mimetype detection)
RUN apk add --no-cache libmagic
# ----------------------------------------------------------------------

FROM fastbpmn-base AS build-python

WORKDIR /home/fastbpmn
ENV UV_PROJECT_ENVIRONMENT="/home/fastbpmn/.venv"

# ----------------------------------------------------------------------
# Make sure to set proper settings for python and pip installation
ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# ----------------------------------------------------------------------


# ----------------------------------------------------------------------
# Install fastbpmn locally (from source) and all requirements
RUN --mount=type=bind,target=/tmp/builder,source=.,readwrite \
    uv venv  \
    && if ls /tmp/builder/dist/*.whl 1> /dev/null 2>&1; then \
         uv pip install /tmp/builder/dist/*.whl; \
       else \
         cd /tmp/builder && uv build && cd /home/fastbpmn/ && uv pip install /tmp/builder/dist/*.whl; \
       fi

ENV PATH="/home/fastbpmn/.venv/bin:$PATH"
# ----------------------------------------------------------------------


FROM fastbpmn-base AS fastbpmn

ARG YIO_fastbpmn_PACKAGE=fastbpmn
ARG YIO_fastbpmn_VERSION=0.0.0

# ----------------------------------------------------------------------
# All following steps are performed as non-root user
USER fastbpmn

# Copy required files for regular version (dependent startup script)
COPY --chown=fastbpmn:fastbpmn docker-images/general/start.py /home/fastbpmn/start.py
COPY --chown=fastbpmn:fastbpmn docker-images/general/start.sh /home/fastbpmn/start.sh
COPY --chown=fastbpmn:fastbpmn docker-images/general/app /home/fastbpmn/app
COPY --chown=fastbpmn:fastbpmn --from=build-python /home/fastbpmn/.venv /home/fastbpmn/.venv

# ----------------------------------------------------------------------
# Make sure to set proper settings for python venv usage
ENV PATH="/home/fastbpmn/.venv/bin:/home/fastbpmn/.local/bin:${PATH}"
# Configure entrypoint and base cmd for fastbpmn startup
ENTRYPOINT ["/home/fastbpmn/start.sh"]
CMD ["run"]
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Add metadata to the image
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vendor="yio gmbh"

LABEL org.label-schema.name="${YIO_fastbpmn_PACKAGE}"
LABEL org.label-schema.version="${YIO_fastbpmn_VERSION}"
LABEL org.label-schema.description="A framework to execute external tasks with ease."
LABEL version="${YIO_fastbpmn_VERSION}"
# ----------------------------------------------------------------------
