name: Build / Publish Documentation
on:
  workflow_call:
    inputs:
      publish:
        description: "Whether to publish docs"
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  verify:
    if: ${{ ! inputs.publish }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.0.0

      - run: |
          cat docs/intermediate/front_matter_changelog.md CHANGELOG.md > docs/docs/changelog.md
        shell: bash

      - run: uv run --only-group docs zensical build --clean
        working-directory: docs

  deploy:
    if: inputs.publish
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.0.0

      - run: |
          cat docs/intermediate/front_matter_changelog.md CHANGELOG.md > docs/docs/changelog.md
        shell: bash

      - run: uv run --only-group docs zensical build --clean
        working-directory: docs
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/site
      - uses: actions/deploy-pages@v4
        id: deployment
