name: Lint & Test
on:
  workflow_call:
    inputs:
      lint:
        description: "Whether to enable linting"
        type: boolean
        default: true

      test:
        description: "Whether to enable testing"
        type: boolean
        default: true

      build:
        description: "Whether to enable building"
        type: boolean
        default: true

      publish:
        description: "Whether to publish any built artifacts"
        type: boolean
        default: false

jobs:

  dev-version:
    if: ${{ inputs.build }}
    uses: ./.github/workflows/version.yaml
    with:
      dev: true

  python-tests:
    if: ${{ inputs.test }}
    needs: dev-version
    strategy:
      fail-fast: false
      matrix:
        tox-env: [py311, py312, py313, py314]
    uses: ./.github/workflows/reusable_tox.yaml
    with:
      dependency_group: 'tox'
      environment: ${{ matrix.tox-env }}

  python-lint:
    if: ${{ inputs.lint }}
    needs: dev-version
    strategy:
      fail-fast: false
      matrix:
        tox-env: [ruff]
    uses: ./.github/workflows/reusable_tox.yaml
    with:
      dependency_group: 'tox'
      environment: ${{ matrix.tox-env }}

  python-build:
    if: ${{ inputs.build }}
    needs: dev-version
    uses: ./.github/workflows/reusable_python-build.yaml
    with:
      version: ${{ needs.dev-version.outputs.bumped_version }}

  docker-build:
    if: ${{ inputs.build }}
    uses: ./.github/workflows/reusable_docker-build.yaml
    needs: [dev-version, python-build]
    with:
      version: ${{ needs.dev-version.outputs.bumped_version }}
      push: ${{ inputs.publish }}
