name: Docker
on:
  workflow_call:
    inputs:
      push:
        description: "Whether to publish any built artifacts"
        type: boolean
        default: false
jobs:
  docker-build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token

      packages: write
      attestations: write
    with:
      output: image
      push: ${{ inputs.push }}
      context: .
      file: ./docker-images/Dockerfile
      target: fastbpmn
      platforms: linux/amd64,linux/arm64
      #cache: true
      #cache-scope: myapp
      meta-images: |
        ghcr.io/${{ github.repository }}

      meta-tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=ref,event=branch
        type=ref,event=pr

        type=sha,enable=true,prefix=,suffix=,format=short
        # define default branch
        type=edge,branch=main
      set-meta-labels: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
