name: Lint & Test
on:
  # Run verify only if non-docs file changes
  # (save resources in case of docs updates)
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

# let verification
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify.yaml
    with:
      build: true
      lint: true
      test: true
      publish: ${{ github.ref == 'refs/heads/main' }}
